apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootdockerproject-deployment
  labels:
    app: bootdockerproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootdockerproject
  template:
    metadata:
      labels:
        app: bootdockerproject
    spec:
      containers:
      - name: helloworld
        image: 127.0.0.1:30400/bootdockerproject:$BUILD_TAG
        ports:
        - containerPort: 8080